---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flux
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: flux
    spec:
      # The serviceAccount is only needed for Kubernetes with RBAC
      # serviceAccount: flux
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
      containers:
      - name: flux
        image: quay.io/weaveworks/flux:master-a26a2f6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030 # informational
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
        args:
        # if you deployed memcached, you can supply these arguments to
        # tell fluxd to use it. You may need to change the namespace
        # (`default`)
        - --memcached-hostname=memcached.default.svc.cluster.local
        - --memcached-timeout=100ms
        - --memcached-service=memcached
        - --registry-cache-expiry=20m
        # replace (at least) the following URL
        - --git-url=git@github.com:ntfrnzn/flux-example
        - --git-branch=helm
        # include these to connect to an "upstream" service (e.g.,
        # Weave Cloud). The token is particular to the service.
        # - --connect=ws://cloud.weave.works/api/flux
        # - --token=abc123abc123abc123abc123
        # override -b and -t arguments to ssh-keygen
        # - --ssh-keygen-bits=2048
        - --ssh-keygen-type=ed25519
